default_platform(:ios)

platform :ios do
  desc "Build & upload to testflight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_filepath: "fastlane/AuthKey.p8",
      in_house: false
    )
    cert
    sigh(
      app_identifier: "com.dawidcompany.simpleweatherapp",
      adhoc: true,
      api_key: api_key
    )

    gym(scheme: "Release")

    upload_to_testflight(
      skip_submission: true,
      api_key: api_key
    )
  end
end
