name: React Native Build
on:
  pull_request:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependecies
        run: yarn install
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Build android app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd ./android && ./gradlew assembleRelease

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm install
          npx pod-install
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild \
            -workspace CkOnboardinApp.xcworkspace \
            -scheme CkOnboardinApp \
            -configuration Release \
            -allowProvisioningUpdates \
            -sdk iphoneos \
            -derivedDataPath build/ \
            clean build
