name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node
  tsc:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run TypeScript compiler
        run: yarn run tsc
  lint:
    runs-on: ubuntu-latest
    needs: [setup-node, tsc]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Linting
        run: yarn run lint
  build:
    runs-on: ubuntu-latest
    needs: [setup-node, tsc, lint]
    steps:
      - name: Build app with fastlane
        run: echo Add fastlane lane for build only without deploy step
